Repository wellcometrust/platform, pull requests merged in 2019-01, with the labels that each got.

#3196 Duplicated Storage VPC inside storage AWS account
  infrastructure/shared/terraform/outputs.tf
  infrastructure/shared/terraform/provider.tf
  infrastructure/shared/terraform/vpcs.tf
Labels: Archive Integration, infrastructure

#3150 realtime reporting
  catalogue_pipeline/terraform/locals.tf
  catalogue_pipeline/terraform/pipelines.tf
  infrastructure/shared/terraform/outputs.tf
  infrastructure/shared/terraform/topics.tf
  reporting/terraform/locals.tf
  reporting/terraform/main.tf
  reporting/terraform/reporting_lambda/main.tf
  reporting/terraform/reporting_lambda/trigger_sns_subscriptions/sns.tf
  reporting/terraform/reporting_lambda/trigger_sns_subscriptions/variables.tf
  reporting/terraform/reporting_lambda/variables.tf
  reporting/terraform/terraform.tf
  sierra_adapter/terraform/bib_merger/outputs.tf
  sierra_adapter/terraform/item_merger/outputs.tf
  sierra_adapter/terraform/outputs.tf
Labels: reporting

#3209 RFC: Add API Architecture
  docs/rfcs/006-reindexer_architecture/README.md
  docs/rfcs/010-data_model/README.md
  docs/rfcs/011-network_architecture/README.md
  docs/rfcs/012-api_architecture/README.md
  docs/rfcs/012-api_architecture/api.wellcomecollection.org.png
Labels: RFC

#3270 Create a new pipeline for the ISBN reindex
  catalogue_pipeline/terraform/pipelines.tf
  catalogue_pipeline/terraform/pipelines/cluster.tf
  catalogue_pipeline/terraform/pipelines/locals.tf
  catalogue_pipeline/terraform/pipelines/main.tf
  catalogue_pipeline/terraform/pipelines/network.tf
  catalogue_pipeline/terraform/pipelines/topics.tf
  catalogue_pipeline/terraform/pipelines/transformers.tf
  catalogue_pipeline/terraform/pipelines/variables.tf
  catalogue_pipeline/terraform/security_groups.tf
  reindexer/start_reindex.py
Labels: 📚Catalogue

#3221 Add an SNS notification step to bag_replicator
  archive/bag_replicator/src/main/resources/application.conf
  archive/bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicator.scala
  archive/bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
  archive/bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/messages/BagReplicationMessage.scala
  archive/bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
  archive/bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
Labels: 📦 Storage service

#3271 Debug the Elasticsearch query in the API; remove unused Logging imports/extends from
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveItemJobCreator.scala
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveChecksumFlow.scala
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/NotificationMessageFlow.scala
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/UploadDigestItemFlow.scala
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/UploadItemFlow.scala
  archive/archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/ZipFileDownloadFlow.scala
  archive/progress_async/src/main/scala/uk/ac/wellcome/platform/archive/progress_async/flows/CallbackNotificationFlow.scala
  archive/registrar_async/src/main/scala/uk/ac/wellcome/platform/archive/registrar/async/factories/StorageManifestFactory.scala
  catalogue_api/api/src/main/scala/uk/ac/wellcome/platform/api/services/ElasticsearchService.scala
  catalogue_pipeline/id_minter/src/main/scala/uk/ac/wellcome/platform/idminter/steps/IdentifierGenerator.scala
  catalogue_pipeline/matcher/src/main/scala/uk/ac/wellcome/platform/matcher/storage/WorkGraphStore.scala
  catalogue_pipeline/merger/src/main/scala/uk/ac/wellcome/platform/merger/services/MergerWorkerService.scala
  sierra_adapter/sierra_bib_merger/src/main/scala/uk/ac/wellcome/platform/sierra_bib_merger/services/SierraBibMergerUpdaterService.scala
  sierra_adapter/sierra_item_merger/src/main/scala/uk/ac/wellcome/platform/sierra_item_merger/services/SierraItemMergerUpdaterService.scala
  sierra_adapter/sierra_reader/src/main/scala/uk/ac/wellcome/platform/sierra_reader/flow/SierraRecordWrapperFlow.scala
Labels: 🚑 Health

#3341 Tidy up some fixtures in the Sierra adapter
  sierra_adapter/sierra_bib_merger/src/test/scala/uk/ac/wellcome/platform/sierra_bib_merger/SierraBibMergerFeatureTest.scala
  sierra_adapter/sierra_bib_merger/src/test/scala/uk/ac/wellcome/platform/sierra_bib_merger/fixtures/WorkerServiceFixture.scala
  sierra_adapter/sierra_bib_merger/src/test/scala/uk/ac/wellcome/platform/sierra_bib_merger/services/SierraBibMergerWorkerServiceTest.scala
Labels: 🚑 Health

#3343 We don't need to wrap this HttpResponse in an option
  storage/notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/flows/CallbackUrlFlow.scala
  storage/notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/flows/PrepareNotificationFlow.scala
  storage/notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/models/CallbackFlowResult.scala
  storage/notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/fixtures/NotifierGenerators.scala
  storage/notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/flows/PrepareNotificationFlowTest.scala
Labels: 🚑 Health

#3342 Cleanups in the storage service
  storage/archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/fixtures/ArchivistFixtures.scala
  storage/bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
  storage/bags/src/test/scala/uk/ac/wellcome/platform/archive/registrar/async/fixtures/RegistrarFixtures.scala
  storage/bags_common/src/main/scala/uk/ac/wellcome/platform/archive/registrar/common/models/StorageManifest.scala
  storage/common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/ArchiveMessaging.scala
  storage/common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/HttpFixtures.scala
  storage/common/src/test/scala/uk/ac/wellcome/platform/archive/common/messaging/MessageStreamTest.scala
  storage/ingests/src/test/scala/uk/ac/wellcome/platform/archive/progress_async/fixtures/ProgressAsyncFixture.scala
  storage/ingests_api/src/test/scala/uk/ac/wellcome/platform/archive/progress_http/ProgressHttpFeatureTest.scala
  storage/notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/fixtures/NotifierFixture.scala
Labels: 🚑 Health

#3355 Remove the GracefulFailureException trait; we don't use it
  catalogue_pipeline/id_minter/src/main/scala/uk/ac/wellcome/platform/idminter/exceptions/IdMinterException.scala
  catalogue_pipeline/ingestor/src/main/scala/uk/ac/wellcome/platform/ingestor/exceptions/IngestorException.scala
  catalogue_pipeline/matcher/src/main/scala/uk/ac/wellcome/platform/matcher/exceptions/MatcherException.scala
  catalogue_pipeline/matcher/src/main/scala/uk/ac/wellcome/platform/matcher/models/VersionConflictException.scala
  catalogue_pipeline/matcher/src/test/scala/uk/ac/wellcome/platform/matcher/matcher/WorkMatcherConcurrencyTest.scala
  catalogue_pipeline/matcher/src/test/scala/uk/ac/wellcome/platform/matcher/workgraph/WorkGraphUpdaterTest.scala
  catalogue_pipeline/transformer/transformer_miro/src/main/scala/uk/ac/wellcome/platform/transformer/miro/exceptions/MiroTransformerException.scala
  catalogue_pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/exceptions/SierraTransformerException.scala
  sbt_common/common/src/main/scala/uk/ac/wellcome/exceptions/GracefulFailureException.scala
  sierra_adapter/sierra_bib_merger/src/test/scala/uk/ac/wellcome/platform/sierra_bib_merger/services/SierraBibMergerWorkerServiceTest.scala
  sierra_adapter/sierra_item_merger/src/main/scala/uk/ac/wellcome/platform/sierra_item_merger/exceptions/SierraItemMergerException.scala
  sierra_adapter/sierra_items_to_dynamo/src/test/scala/uk/ac/wellcome/platform/sierra_items_to_dynamo/services/SierraItemsToDynamoWorkerServiceTest.scala
  sierra_adapter/sierra_reader/src/main/scala/uk/ac/wellcome/platform/sierra_reader/exceptions/SierraReaderException.scala
Labels: 🚑 Health

#3378 We don't need to create a reindexShard GSI in the reindexer tests
  builds/sbt_metadata/api.json
  builds/sbt_metadata/archivist.json
  builds/sbt_metadata/bag_replicator.json
  builds/sbt_metadata/bags.json
  builds/sbt_metadata/bags_api.json
  builds/sbt_metadata/bags_common.json
  builds/sbt_metadata/common.json
  builds/sbt_metadata/config_core.json
  builds/sbt_metadata/config_elasticsearch.json
  builds/sbt_metadata/config_messaging.json
  builds/sbt_metadata/config_monitoring.json
  builds/sbt_metadata/config_storage.json
  builds/sbt_metadata/display.json
  builds/sbt_metadata/elasticsearch.json
  builds/sbt_metadata/goobi_reader.json
  builds/sbt_metadata/id_minter.json
  builds/sbt_metadata/ingestor.json
  builds/sbt_metadata/ingests.json
  builds/sbt_metadata/ingests_api.json
  builds/sbt_metadata/ingests_common.json
  builds/sbt_metadata/internal_model.json
  builds/sbt_metadata/matcher.json
  builds/sbt_metadata/merger.json
  builds/sbt_metadata/notifier.json
  builds/sbt_metadata/recorder.json
  builds/sbt_metadata/reindex_worker.json
  builds/sbt_metadata/sierra_adapter_common.json
  builds/sbt_metadata/sierra_bib_merger.json
  builds/sbt_metadata/sierra_item_merger.json
  builds/sbt_metadata/sierra_items_to_dynamo.json
  builds/sbt_metadata/sierra_reader.json
  builds/sbt_metadata/snapshot_generator.json
  builds/sbt_metadata/storage_common.json
  builds/sbt_metadata/storage_display.json
  builds/sbt_metadata/transformer_miro.json
  builds/sbt_metadata/transformer_sierra.json
  reindexer/reindex_worker/src/test/scala/uk/ac/wellcome/platform/reindex/reindex_worker/fixtures/ReindexableTable.scala
Labels: 🚑 Health
